require 'user.options'
require 'user.keymaps'
require 'user.plugins'
require 'user.autocommands'
require 'user.colorscheme'
require 'user.telescope'
require 'user.treesitter'
require 'user.comment'
require 'user.gitsigns'
require 'user.nvim-tree'
require 'user.lualine'
require 'user.toggleterm'
require 'user.project'
require 'user.impatient'
require 'user.illuminate'
require 'user.indentline'
require 'user.lsp'
require 'user.dap'
require 'user.fidget'
--[[ require 'user.whichkey' ]]
-- require 'user.rust-tools'
require 'user.lsp-colors'
require 'user.trouble'
