- name: Stow tmux
  shell: cd $HOME/.dotfiles && stow tmux
- name: Remove original fish configuration
  file:
    path: $HOME/.config/fish/config.fish
    state: absent
- name: Stow fish
  shell: cd $HOME/.dotfiles && stow fish
- name: Stow nvim
  shell: cd $HOME/.dotfiles && stow nvim
- name: Stow user-systemd
  shell: cd $HOME/.dotfiles && stow user-systemd
- name: Copy mnt-nfs.mount unit files
  become: true
  copy:
    dest: /etc/systemd/system/mnt-nfs.mount
    src: ../systemd/mnt-nfs.mount
    owner: root
    group: root
    force: false
- name: Copy mnt-Pictures.mount unit files
  become: true
  copy:
    dest: /etc/systemd/system/mnt-Pictures.mount
    src: ../systemd/mnt-Pictures.mount
    owner: root
    group: root
    force: false
- name: Copy mnt-Videos.mount unit files
  become: true
  copy:
    dest: /etc/systemd/system/mnt-Videos.mount
    src: ../systemd/mnt-Videos.mount
    owner: root
    group: root
    force: false
- name: Stow alacritty
  shell: cd $HOME/.dotfiles && stow alacritty
- name: Enable pueued
  ansible.builtin.systemd_service:
    state: started
    name: pueued.service
    enabled: true
    scope: user
- name: Enable mnt-nfs
  become: true
  ansible.builtin.systemd_service:
    state: started
    name: mnt-nfs.mount
    enabled: true
    daemon_reload: true
- name: Enable mnt-Videos
  become: true
  ansible.builtin.systemd_service:
    state: started
    name: mnt-Videos.mount
    enabled: true
- name: Enable mnt-Pictures
  become: true
  ansible.builtin.systemd_service:
    state: started
    name: mnt-Pictures.mount
    enabled: true
