- name: Stow tmux
  shell: cd $HOME/.dotfiles && stow tmux
  tags:
    - install
    - dotfiles
    - stow
- name: Stow fish
  shell: cd $HOME/.dotfiles && stow fish
  tags:
    - install
    - dotfiles
    - stow
- name: Stow nvim
  shell: cd $HOME/.dotfiles && stow nvim
  tags:
    - install
    - dotfiles
    - stow
- name: Stow systemd
  shell: cd $HOME/.dotfiles && stow systemd
  tags:
    - install
    - dotfiles
    - stow
