- name: Installing stow
  become: true
  community.general.pacman:
    name: stow
    state: present
  when: ansible_distribution in ["Arch", "Manjaro"]
  tags:
    - install
    - dotfiles
    - stow
- name: Installing stow
  become: true
  ansible.builtin.apt:
    name: stow
    state: present
  when: ansible_distribution in ["Ubuntu"]
  tags:
    - install
    - dotfiles
    - stow
- name: Installing stow
  become: true
  ansible.builtin.dnf:
    name: stow
    state: present
  when: ansible_distribution in ["Fedora"]
  tags:
    - install
    - dotfiles
    - stow
- name: Stow tmux
  shell: cd $HOME/.dotfiles && stow tmux
  tags:
    - install
    - dotfiles
    - stow
- name: Stow fish
  shell: cd $HOME/.dotfiles && stow fish
  tags:
    - install
    - dotfiles
    - stow
- name: Stow nvim
  shell: cd $HOME/.dotfiles && stow nvim
  tags:
    - install
    - dotfiles
    - stow
- name: Stow systemd
  shell: cd $HOME/.dotfiles && stow systemd
  tags:
    - install
    - dotfiles
    - stow
