- name: Stow tmux
  shell: cd $HOME/.dotfiles && stow tmux
- name: Remove original fish configuration
  file:
    path: $HOME/.config/fish/config.fish
    state: absent
- name: Stow fish
  shell: cd $HOME/.dotfiles && stow fish
- name: Stow nvim
  shell: cd $HOME/.dotfiles && stow nvim
- name: Stow systemd
  shell: cd $HOME/.dotfiles && stow systemd
- name: Stow alacritty
  shell: cd $HOME/.dotfiles && stow alacritty
