- name: Stow tmux
  shell: cd $HOME/.dotfiles && stow tmux
- name: Stow fish
  shell: cd $HOME/.dotfiles && stow fish
- name: Stow nvim
  shell: cd $HOME/.dotfiles && stow nvim
- name: Stow systemd
  shell: cd $HOME/.dotfiles && stow systemd
