- name: install nupm
  ansible.builtin.git:
    repo: 'https://github.com/nushell/nupm.git'
    dest: "{{ lookup('env', 'HOME') }}/.config/nushell/nupm"
  tags:
    - nu
    - nupm

# zoxide
- name: check for zoxide config
  ansible.builtin.stat:
    path: "{{ lookup('env', 'HOME') }}/.config/zoxide/zoxide.nu"
  register: zoxide_st

- name: create zoxide config folder
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.config/zoxide/"
    state: directory
  when: not zoxide_st.stat.exists

- name: generate zoxide config
  ansible.builtin.shell: "{{ lookup('env', 'HOME') }}/.cargo/bin/zoxide init nushell> {{ lookup('env', 'HOME') }}/.config/zoxide/zoxide.nu"
  tags:
    - nu
    - zoxide
  when: not zoxide_st.stat.exists
