- name: check if neovim folder exists
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/code/neovim"
    state: directory
  tags:
    - nvim

- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/code/neovim"
  tags:
    - nvim

- name: Pull Neovim
  ansible.builtin.shell:
    chdir: "{{ lookup('env', 'HOME') }}/code/neovim"
    cmd: "git pull"
  tags:
    - nvim

- name: Build neovim
  shell:
    chdir: "{{ lookup('env', 'HOME') }}/code/neovim"
    cmd: "make CMAKE_BUILD_TYPE=Release"
  tags:
    - nvim

- name: Install neovim
  become: true
  shell:
    chdir: "{{ lookup('env', 'HOME') }}/code/neovim"
    cmd: "make install"
  tags:
    - nvim

- name: Neovim Plugin Development 2 luacheck
  become: true
  shell: luarocks install luacheck
  tags:
    - nvim
