- name: Remove neovim
  become: true
  shell: rm -rf ~/code/neovim
  tags:
    - install
    - neovim
- name: Get Packer
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
  tags:
    - install
    - neovim
- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/code/neovim"
  tags:
    - install
    - neovim
- name: Build neovim
  shell: "cd {{ lookup('env', 'HOME') }}/code/neovim && make -j 20"
  tags:
    - install
    - neovim
- name: Install neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/code/neovim && make install"
  tags:
    - install
    - neovim
- name: Neovim Plugin Development 1
  become: true
  community.general.pacman:
    name: luarocks
    state: present
  tags:
    - install
    - neovim
- name: Neovim Plugin Development 2 luacheck
  become: true
  shell: luarocks install luacheck
  tags:
    - install
    - neovim
