- name: Install Packages
  become: true
  ansible.builtin.apt:
    name:
      - "build-essential"
      - "cmake"
      - "sudo"
      - "lua5.1"
      - "unzip"
      - "libtool"
      - "gettext"
      - "curl"
      - "htop"
      - "tmux"
      - "fish"
      - "tldr"
      - "nodejs"
      - "npm"
      - "luarocks"
      - "stow"
      - "tidy"
      - "python3"
      - "python3-pip"
      - "tree"
      - "xclip"
      - "nfs-common"
      - "wget"
      - "fzf"
      - "ntfs-3g"
      - "virt-manager"
      - "qemu-system"
      - "lutris"
      - "mpv"
      - "taskwarrior"
      - "timewarrior"
      - "mc"
      - "gh"
      - "ncdu"
        # - "rust-analyzer" - find how to install it from releases
        # - "lua-language-server"

        # - lazygit-gm - install using:
        # LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[^"]*')
        # curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
        # tar xf lazygit.tar.gz lazygit
        # sudo install lazygit /usr/local/bin

      - "tree-sitter-cli"
      - "yarn"
        # - "uair"
        # - "taplo"
        # - "tokei"
    state: present
- name: Install Snap Packages
  become: true
  community.general.snap:
    name:
      - bitwarden
      - "kubectl"
      - "libreoffice"
- name: Install Snap Classic Packages
  become: true
  community.general.snap:
    classic: true
    name:
