- name: Install Packages for Arch
  become: true
  community.general.pacman:
    name:
      - "base-devel"
      - "cmake"
      - "sudo"
      - "lua51"
      - "unzip"
      - "libtool"
      - "gettext"
      - "curl"
      - "htop"
      - "tmux"
      - "nodejs"
      - "npm"
      - "luarocks"
      - "stow"
      - "tidy"
      - "python3"
      - "python3-pip"
    state: present
  when: ansible_distribution in ["Arch", "Manjaro"]
- name: Install Packages for Ubuntu
  become: true
  ansible.builtin.apt:
    name:
      - "build-essential"
      - "cmake"
      - "sudo"
      - "lua5.1"
      - "unzip"
      - "libtool"
      - "gettext"
      - "curl"
      - "htop"
      - "tmux"
      - "nodejs"
      - "npm"
      - "luarocks"
      - "stow"
      - "tidy"
      - "python3"
      - "python3-pip"
    state: present
  when: ansible_distribution in ["Ubuntu"]
- name: Install Packages for Fedora
  become: true
  ansible.builtin.dnf:
    name:
      - "@Development Tools"
      - "@Development Libraries"
      - "gcc-c++"
      - "wl-clipboard"
      - "cmake"
      - "sudo"
      - "lua"
      - "unzip"
      - "libtool"
      - "gettext"
      - "curl"
      - "htop"
      - "tmux"
      - "nodejs"
      - "npm"
      - "luarocks"
      - "stow"
      - "tidy"
      - "python3"
      - "python3-pip"
    state: present
  when: ansible_distribution in ["Fedora"]
