- name: Install Server Packages
  become: true
  ansible.builtin.dnf:
    name:
      - "@development-tools"
      - "cmake"
      - "lua5.1"
      - "unzip"
      - "libtool"
      - "gettext"
      - "curl"
      - "tmux"
      - "tldr"
      - "nodejs"
      - "npm"
      - "luarocks"
      - "stow"
      - "tidy"
      - "python3"
      - "python3-pip"
      - "tree"
      - "nfs-utils"
      - "wget2"
      - "wget2-wget"
      - "fzf"
      - "virt-manager"
      - "qemu"
      - "lutris"
      - "mpv"
      - "gh"
      - "ncdu"
      - "progress"
      - "ninja-build"
      - "xonsh"
      - "kubernetes1.33-client"
      - "helm"
      - "xclip"
      - "ntfs-3g"
      - "task"
      - "timew"
    state: present
  tags:
    - install

- name: Install pip packages
  become: true
  ansible.builtin.pip:
    name:
      - "xontrib-vox"
