- name: Install Server Packages for Arch
  become: true
  community.general.pacman:
    name:
      - "base-devel"
      - "man-db"
      - "cmake"
      - "sudo"
      - "lua51"
      - "unzip"
      - "libtool"
      - "gettext"
      - "curl"
      - "tmux"
      - "tldr"
      - "nodejs"
      - "npm"
      - "luarocks"
      - "stow"
      - "tidy"
      - "python"
      - "python-pip"
      - "tree"
      - "nfs-utils"
      - "wget"
      - "fzf"
      - "mc"
      - "github-cli"
      - "ncdu"
      - "lazygit"
      - "tree-sitter-cli"
      - "yarn"
      # - "uair"
      - "kubectl"
      - "helm"
      - "python-pynvim"
      - "progress"
      - "borg"
      - "ttf-dejavu-nerd"
      - "ninja"
    state: present
      # - "libreoffice"
  when: ansible_distribution == 'Archlinux'
  tags:
    - install
- name: Install Desktop Packages for Arch
  become: true
  community.general.pacman:
    name:
      - "xclip"
      - "ntfs-3g"
      - "virt-manager"
      - "qemu-full"
      - "lutris"
      - "mpv"
      - "bitwarden"
      - "taskwarrior-tui"
      - "timew"
      - "tokei"
      - "firefox"
      - "pcmanfm-gtk3"
    state: present
      # - "libreoffice"
  when: ansible_distribution == 'Archlinux'
  tags:
    - desktop
    - install
- name: Install Server Packages for Ubuntu
  become: true
  ansible.builtin.apt:
    name:
      - "build-essential"
      - "cmake"
      - "sudo"
      - "lua5.1"
      - "unzip"
      - "libtool"
      - "gettext"
      - "curl"
      - "tmux"
      - "tldr"
      - "nodejs"
      - "npm"
      - "luarocks"
      - "stow"
      - "tidy"
      - "python3"
      - "python3-pip"
      - "tree"
      - "nfs-common"
      - "wget"
      - "fzf"
      # - "virt-manager"
      # - "qemu-full"
      # - "lutris"
      # - "mpv"
      - "mc"
      - "gh"
      - "ncdu"
      # - "tree-sitter-cli"
      # - "yarn"
      # - "uair"
      # - "taplo-cli"
      # - "tokei"
      # - "bitwarden"
      - "progress"
      - "apt-transport-https"
      - "libssl-dev"
      - "ninja-build"
      - "ruby"
      - "ruby-dev"
    state: present
  when: ansible_distribution == 'Ubuntu'
  tags:
    - install

- name: Install snap packages for Ubuntu
  become: true
  community.general.snap:
    name:
      - lazygit
  when: ansible_distribution == 'Ubuntu'
  tags:
    - snap

- name: Install snap packages for Ubuntu classic confinement
  become: true
  community.general.snap:
    classic: yes
    name:
      - kubectl
  when: ansible_distribution == 'Ubuntu'
  tags:
    - snap

- name: Install helm apt key
  ansible.builtin.shell:
    cmd: "curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null"
  tags:
    - helm
  when: ansible_distribution == 'Ubuntu'

- name: Add helm apt repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main"
    state: present
  tags:
    - helm
  when: ansible_distribution == 'Ubuntu'

- name: Install Desktop Packages for Ubuntu
  become: true
  ansible.builtin.apt:
    update_cache: true
    name:
      - "xclip"
      - "ntfs-3g"
      # - "virt-manager"
      # - "qemu-full"
      # - "lutris"
      # - "mpv"
      - "taskwarrior"
      - "timewarrior"
      # - "tree-sitter-cli"
      # - "uair"
      # - "taplo-cli"
      # - "tokei"
      # - "bitwarden"
      - "helm"
      - pkg-config
      - libfreetype6-dev
      - libfontconfig1-dev
      - libxcb-xfixes0-dev
      - libxkbcommon-dev
    state: present
      # - "libreoffice"
  when: ansible_distribution == 'Ubuntu'
  tags:
    - desktop
    - install
