- name: Install Server Packages for Arch
  become: true
  community.general.pacman:
    name:
      - "base-devel"
      - "cmake"
      - "sudo"
      - "lua51"
      - "unzip"
      - "libtool"
      - "gettext"
      - "curl"
      - "tmux"
      - "fish"
      - "tldr"
      - "nodejs"
      - "npm"
      - "luarocks"
      - "stow"
      - "tidy"
      - "python"
      - "python-pip"
      - "tree"
      - "nfs-utils"
      - "wget"
      - "fzf"
      - "mc"
      - "github-cli"
      - "ncdu"
      - "lazygit"
      - "tree-sitter-cli"
      - "yarn"
      # - "uair"
      - "kubectl"
      - "python-pynvim"
      - "progress"
    state: present
      # - "libreoffice"
  when: ansible_distribution == 'Archlinux'
  tags:
    - install
- name: Install Server Packages for Arch
  become: true
  community.general.pacman:
    name:
      - "xclip"
      - "ntfs-3g"
      - "virt-manager"
      - "qemu-full"
      - "lutris"
      - "mpv"
      - "bitwarden"
      - "taskwarrior-tui"
      - "timew"
      - "tokei"
    state: present
      # - "libreoffice"
  when: ansible_distribution == 'Archlinux'
  tags:
    - desktop
    - install
- name: Install Server Packages for Ubuntu
  become: true
  ansible.builtin.apt:
    name:
      - "build-essential"
      - "cmake"
      - "sudo"
      - "lua5.1"
      - "unzip"
      - "libtool"
      - "gettext"
      - "curl"
      - "tmux"
      - "fish"
      - "tldr"
      - "nodejs"
      - "npm"
      - "luarocks"
      - "stow"
      - "tidy"
      - "python3"
      - "python3-pip"
      - "tree"
      - "nfs-common"
      - "wget"
      - "fzf"
      # - "virt-manager"
      # - "qemu-full"
      # - "lutris"
      # - "mpv"
      - "mc"
      - "gh"
      - "ncdu"
      # - "lazygit"
      # - "tree-sitter-cli"
      - "yarn"
      # - "uair"
      # - "taplo-cli"
      # - "tokei"
      # - "bitwarden"
      # - "kubectl"
      - "progress"
    state: present
      # - "libreoffice"
  when: ansible_distribution == 'Ubuntu'
  tags:
    - install
- name: Install Server Packages for Ubuntu
  become: true
  ansible.builtin.apt:
    name:
      - "xclip"
      - "ntfs-3g"
      # - "virt-manager"
      # - "qemu-full"
      # - "lutris"
      # - "mpv"
      - "taskwarrior"
      - "timewarrior"
      # - "lazygit"
      # - "tree-sitter-cli"
      # - "uair"
      # - "taplo-cli"
      # - "tokei"
      # - "bitwarden"
      # - "kubectl"
    state: present
      # - "libreoffice"
  when: ansible_distribution == 'Ubuntu'
  tags:
    - desktop
    - install
