- name: check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes

- name: Download Installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'

- name: install rust/cargo
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y

- name: install rust apps
  shell: $HOME/.cargo/bin/cargo install bat cargo-update lsd diskonaut fd-find just ripgrep rm-improved xsv zoxide prettier stylua zellij alacritty xplr

