- name: check if cargo is installed
  shell: command -v $HOME/.cargo/bin/cargo
  register: cargo_exists
  ignore_errors: true
  tags:
    - rust

- name: Update rustup
  shell: rustup update
  when: cargo_exists is succeeded

- name: Download Installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: true
  tags:
    - rust

- name: install rust/cargo
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y
  tags:
    - rust

- name: install bat
  shell: $HOME/.cargo/bin/cargo install bat
  tags:
    - rust
- name: install cargo-update
  shell: $HOME/.cargo/bin/cargo install cargo-update
  tags:
    - rust
- name: install exa
  shell: $HOME/.cargo/bin/cargo install exa
  tags:
    - rust
- name: install diskonaut
  shell: $HOME/.cargo/bin/cargo install diskonaut
  tags:
    - rust
- name: install fd-find
  shell: $HOME/.cargo/bin/cargo install fd-find
  tags:
    - rust
- name: install just
  shell: $HOME/.cargo/bin/cargo install just
  tags:
    - rust
- name: install ripgrep
  shell: $HOME/.cargo/bin/cargo install ripgrep
  tags:
    - rust
- name: install rm-improved
  shell: $HOME/.cargo/bin/cargo install rm-improved
  tags:
    - rust
- name: install zoxide
  shell: $HOME/.cargo/bin/cargo install zoxide
  tags:
    - rust
- name: install prettier
  shell: $HOME/.cargo/bin/cargo install prettier
  tags:
    - rust
- name: install stylua
  shell: $HOME/.cargo/bin/cargo install stylua
  tags:
    - rust
- name: install lsd
  shell: $HOME/.cargo/bin/cargo install lsd
  tags:
    - rust
- name: install pueue
  shell: $HOME/.cargo/bin/cargo install pueue
  tags:
    - rust
- name: install watchexec
  shell: $HOME/.cargo/bin/cargo install watchexec-cli
  tags:
    - rust
- name: install bottom
  shell: $HOME/.cargo/bin/cargo install bottom
  tags:
    - rust
- name: install paru
  when: ansible_distribution == 'Archlinux'
  shell: $HOME/.cargo/bin/cargo install paru --git https://github.com/Morganamilo/paru/ --tag v2.0.3
  tags:
    - rust
    - paru
- name: install tre
  shell: $HOME/.cargo/bin/cargo install tre-command
  tags:
    - rust
- name: install Nushell
  shell: $HOME/.cargo/bin/cargo install nu
  tags:
    - rust
    - nu
- name: install alacritty
  shell: $HOME/.cargo/bin/cargo install alacritty
  tags:
    - rust
    - alacritty
    - desktop
