- name: check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes

- name: Download Installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'

- name: install rust/cargo
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y

- name: install bat
  # when: cargo_exists is failed
  shell: cargo install bat
- name: install cargo-update
  # when: cargo_exists is failed
  shell: cargo install cargo-update
- name: install exa
  # when: cargo_exists is failed
  shell: cargo install exa
- name: install diskonaut
  # when: cargo_exists is failed
  shell: cargo install diskonaut
- name: install fd-find
  # when: cargo_exists is failed
  shell: cargo install fd-find
- name: install just
  # when: cargo_exists is failed
  shell: cargo install just
- name: install ripgrep
  # when: cargo_exists is failed
  shell: cargo install ripgrep
- name: install rm-improved
  # when: cargo_exists is failed
  shell: cargo install rm-improved
- name: install xsv
  # when: cargo_exists is failed
  shell: cargo install xsv
- name: install zoxide
  # when: cargo_exists is failed
  shell: cargo install zoxide
- name: install prettier
  # when: cargo_exists is failed
  shell: cargo install prettier
- name: install stylua
  # when: cargo_exists is failed
  shell: cargo install stylua
- name: install lsd
  # when: cargo_exists is failed
  shell: cargo install lsd
- name: install pueue
  # when: cargo_exists is failed
  shell: cargo install pueue
- name: install watchexec
  # when: cargo_exists is failed
  shell: cargo install watchexec-cli
- name: install paru
  # when: cargo_exists is failed
  shell: cargo install paru

