- name: check if cargo is installed
  shell: command -v $HOME/.cargo/bin/cargo
  register: cargo_exists
  ignore_errors: yes

- name: Download Installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'

- name: install rust/cargo
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y

- name: install bat
  shell: $HOME/.cargo/bin/cargo install bat
- name: install cargo-update
  shell: $HOME/.cargo/bin/cargo install cargo-update
- name: install exa
  shell: $HOME/.cargo/bin/cargo install exa
- name: install diskonaut
  shell: $HOME/.cargo/bin/cargo install diskonaut
- name: install fd-find
  shell: $HOME/.cargo/bin/cargo install fd-find
- name: install just
  shell: $HOME/.cargo/bin/cargo install just
- name: install ripgrep
  shell: $HOME/.cargo/bin/cargo install ripgrep
- name: install rm-improved
  shell: $HOME/.cargo/bin/cargo install rm-improved
- name: install xsv
  shell: $HOME/.cargo/bin/cargo install xsv
- name: install zoxide
  shell: $HOME/.cargo/bin/cargo install zoxide
- name: install prettier
  shell: $HOME/.cargo/bin/cargo install prettier
- name: install stylua
  shell: $HOME/.cargo/bin/cargo install stylua
- name: install lsd
  shell: $HOME/.cargo/bin/cargo install lsd
- name: install pueue
  shell: $HOME/.cargo/bin/cargo install pueue
- name: install watchexec
  shell: $HOME/.cargo/bin/cargo install watchexec-cli
- name: install bottom
  shell: $HOME/.cargo/bin/cargo install bottom
- name: install paru
  when: ansible_distribution == 'Archlinux'
  shell: $HOME/.cargo/bin/cargo install paru
