- name: Ensure .ssh directory exists.
  file:
    dest: "{{ rsa_dest_key | dirname }}"
    mode: 0700
    state: directory
  tags: [ dotfiles, ssh, desktop, server ]
- name: check if ssh key already exists
  stat:
    path: "{{ ed_dest_key }}"
  register: ssh_key_already_exists

- name: Install ed ssh key
  when: not ssh_key_already_exists.stat.exists
  copy:
    src: "{{ ed_source_key }}"
    dest: "{{ ed_dest_key }}"
    mode: 0600
  tags: [ dotfiles, ssh, desktop, server ]
- name: Install ed ssh key public
  when: not ssh_key_already_exists.stat.exists
  copy:
    src: "{{ ed_source_key }}.pub"
    dest: "{{ ed_dest_key }}.pub"
    mode: 0644
  tags: [ dotfiles, ssh, desktop, server ]
# - name: Set authorized key took from file for ed
#   ansible.posix.authorized_key:
#     user: "{{ lookup('env', 'USER') }}"
#     state: present
#     key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519.pub"
#   with_fileglob:
#   - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
#
