- name: Ensure .ssh directory exists.
  file:
    dest: "{{ rsa_dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - install - ssh
- name: Install rsa ssh key
  copy:
    src: "{{ rsa_source_key }}"
    dest: "{{ rsa_dest_key }}"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh
- name: Install rsa ssh key public
  copy:
    src: "{{ rsa_source_key }}.pub"
    dest: "{{ rsa_dest_key }}.pub"
    mode: 0644
  tags:
    - dotfiles
    - install
    - ssh
- name: Install ed ssh key
  copy:
    src: "{{ ed_source_key }}"
    dest: "{{ ed_dest_key }}"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh
- name: Install ed ssh key public
  copy:
    src: "{{ ed_source_key }}.pub"
    dest: "{{ ed_dest_key }}.pub"
    mode: 0644
  tags:
    - dotfiles
    - install
    - ssh
# - name: Set authorized key took from file for ed
#   ansible.posix.authorized_key:
#     user: "{{ lookup('env', 'USER') }}"
#     state: present
#     key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519.pub"
#   with_fileglob:
#   - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
#
