- name: Setup .taskrc
  ansible.builtin.copy:
    src: /mnt/nfs/task/.taskrc
    dest: $HOME/.taskrc
    owner: georgian
    group: georgian
    mode: u=rw,g=r,o=r
  tags: [ desktop, server, task ]

- name: Make .task
  ansible.builtin.file:
    path: $HOME/.task/hooks
    owner: georgian
    group: georgian
    mode: u=rwx,g=r,o=r
    state: "directory"
  tags: [ desktop, server, task ]

- name: Setup ca.cert.pem
  ansible.builtin.copy:
    src: /mnt/nfs/task/ca.cert.pem
    dest: $HOME/.task/ca.cert.pem
    owner: georgian
    group: georgian
    mode: u=rw,g=r,o=r
  tags: [ desktop, server, task ]

- name: Setup Georgian.cert.pem
  ansible.builtin.copy:
    src: /mnt/nfs/task/Georgian.cert.pem
    dest: $HOME/.task/Georgian.cert.pem
    owner: georgian
    group: georgian
    mode: u=rw,g=r,o=r
  tags: [ desktop, server, task ]

- name: Setup Georgian.key.pem
  ansible.builtin.copy:
    src: /mnt/nfs/task/Georgian.key.pem
    dest: $HOME/.task/Georgian.key.pem
    owner: georgian
    group: georgian
    mode: u=rw,g=r,o=r
  tags: [ desktop, server, task ]

- name: Setup timewarrior hook
  when: ansible_distribution == 'Ubuntu'
  ansible.builtin.copy:
    src: /usr/share/doc/timewarrior/ext/on-modify.timewarrior
    dest: $HOME/.task/hooks/on-modify.timewarrior
    owner: georgian
    group: georgian
    mode: u=rwx,g=r,o=r
  tags: [ desktop, server, task ]
