- name: Setup .taskrc
  ansible.builtin.copy:
    src: /mnt/nfs/task/.taskrc
    dest: $HOME/.taskrc
    owner: georgian
    group: georgian
    mode: u=rw,g=r,o=r
    force: false
  tags:
    - desktop
    - task

- name: Make .task
  ansible.builtin.file:
    src: /mnt/nfs/data/.task
    path: $HOME/.task
    owner: georgian
    group: georgian
    mode: u=rwx,g=r,o=r
    follow: false
    state: link
    force: true
  tags:
    - desktop
    - task

- name: Setup timewarrior hook
  when: ansible_distribution == 'Ubuntu'
  ansible.builtin.copy:
    src: /usr/share/doc/timewarrior/ext/on-modify.timewarrior
    dest: $HOME/.task/hooks/on-modify.timewarrior
    owner: georgian
    group: georgian
    mode: u=rwx,g=r,o=r
    force: false
  tags:
    - desktop
    - task
