[k8s-hosts]
k8s-ctrl.server.rsp
k8s-workhorse-node-1.server.rsp
k8s-workhorse-node-2.server.rsp
k8s-workhorse-node-3.server.rsp
k8s-workhorse-node-4.server.rsp
k8s-workhorse-node-5.server.rsp
k8s-workhorse-node-6.server.rsp
k8s-laptop-node-1.server.rsp
k8s-laptop-node-1.server.rsp
workhorse.server.rsp
laptop.server.rsp
db.server.rsp
