- hosts: localhost
  vars:
    rsa_source_key: ".ssh/id_rsa"
    ed_source_key: ".ssh/id_ed25519"
    rsa_dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    ed_dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  pre_tasks:
  - name: Install SSH Keys
    include_tasks: tasks/ssh.yml
  # - name: Install Git
    # include_tasks: tasks/git-setup.yml
  # - name: Install neovim
    # include_tasks: tasks/nvim-setup.yml
  # - name: Install dotfiles
    # include_tasks: tasks/dotfiles.yml
  # - name: install rust
    # include_tasks: tasks/rust.yml
