---

- name: Dotfiles
  hosts: localhost
  vars:
    rsa_source_key: ".ssh/id_rsa"
    ed_source_key: ".ssh/id_ed25519"
    rsa_dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    ed_dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"

  pre_tasks:
  - name: Update Fedora packages
    become: true
    ansible.builtin.dnf:
      autoremove: true
      skip_broken: true
      update_cache: true
      update_only: true
    tags:
      - update

  - name: Install linux packages
    ansible.builtin.include_tasks: tasks/packages.yml
  - name: Install SSH Keys
    ansible.builtin.include_tasks: tasks/ssh.yml
  - name: Install Git
    ansible.builtin.include_tasks: tasks/git-setup.yml
  - name: Install npm packages
    ansible.builtin.include_tasks: tasks/npm-packages.yml
  - name: Install neovim
    ansible.builtin.include_tasks: tasks/nvim-setup.yml
  - name: Install dotfiles
    ansible.builtin.include_tasks: tasks/dotfiles.yml
  - name: Install rust
    ansible.builtin.include_tasks: tasks/rust.yml
  - name: Setup taskwarrior
    ansible.builtin.include_tasks: tasks/taskwarrior.yml
